package com.example.pockettrack.data

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "transactions")
data class Transaction(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val title: String,
    val amount: Double,
    val type: String,           // "Income" or "Expense"
    val categoryId: Int,
    val currency: String,       // "USD", "SGD", "IDR"
    val amountInUsd: Double,    // normalized for comparison
    val date: String,           // "yyyy-MM-dd"
    val note: String = "",
    val category: String = "",

    // ── Recurring expense fields ──────────────────────────────────────────
    // isRecurring: marks this row as the recurring template (not deducted itself)
    val isRecurring: Boolean = false,
    // Day of month on which this expense auto-deducts (1–31)
    val recurringDay: Int = 0,
    // Start month/year: auto-deduction begins from this month onward
    val recurringMonth: Int = 0,
    val recurringYear: Int = 0,
    // isAutoGenerated: true for transactions created by the recurring engine
    val isAutoGenerated: Boolean = false,
    // recurringSourceId: links an auto-generated tx back to its template
    val recurringSourceId: Int = 0
)
